### ISSUE TITLE
Проверить выполнение ДЗ по курсу Jmix

### ISSUE THREAD

**Issue by urjadovaa** [urjadovaa/jmix-homework-user-interface-master#1]

**Comment by glebfox** [comment]
**RequestLoan**

В нажатия кнопки `Request` экран стоит закрывать с `StandardOutcome.COMMIT`, чтобы вызывающий код мог понять сохранили мы что то или просто закрыли экран.

Не стоит миксовать аннотацию `@DialogMode` и XML элемент `<dialogMode>`. Лучше все настраивать в одном месте. 

В принципе создавать instance container в этом экране не обязательно, хотя со своей задачей он справляется. 

**LoanApproval**

Не стоит кнопкам задавать фиксированную ширину, т.к. в разных локализациях одни и те же слова имеют разную длину. Уже сейчас у кнопки Approve отступы разные получаются. 

<img width="252" alt="Screenshot 2023-05-12 at 12 44 10" src="https://github.com/urjadovaa/jmix-homework-user-interface-master/assets/6077149/1ca95eda-6456-4418-8f9e-d3aa36047857">

**Comment by urjadovaa** [comment]
Замечания по ДЗ "Loans" устранены.
